### ISSUE TITLE
can you list bios settings?

### ISSUE THREAD

**Issue by g1im2** [SkyrilHD/Dell-Exx50-Hackintosh#1]
hi, my book model is 3450 and I want to try it with your efi, thanks to you to publish it. but, I read this profile and can't found bios settings. can you list it on profile, thanks.

**Comment by SkyrilHD** [comment]
Hey,

Sure.

**General:**
- Boot sequence -> Boot List Option: UEFI

**System configuration:**
- Parallel Port: Disabled
- Serial Port: Disabled
- SATA Operation: AHCI

**Security:**
- TPM Security: Off

**Secure Boot:**
- Secure Boot: Disabled

**Power Management:**
- Wake on LAN/WLAN: Disabled
- USB Wake Support: Off

**Comment by SkyrilHD** [comment]
By the way, is there any update to your 3450? Does it work?
