### ISSUE TITLE
Laptop goes to sleep and interrupts the installation

### ISSUE THREAD

**Issue by KenWuqianghao** [SkyrilHD/Dell-Exx50-Hackintosh#10]
I was able to successfully boot with the USB and get into the installation phase, but while I'm waiting, my laptop goes to sleep after very short period of time and interrupts the installation. Is there a way to keep it awake while installing?

**Comment by SkyrilHD** [comment]
Normally during installation the laptop shouldn't go to sleep. There is something wrong on your end...

Maybe one way to prevent is to press a random key

**Comment by KenWuqianghao** [comment]
I thinking about creating a full installer. Would that work?

**Comment by SkyrilHD** [comment]
Yep it would

**Comment by KenWuqianghao** [comment]
You have any ideas on how to create a big sure full installer? Current guides seem to only support recovery installers, which takes hours to install

**Comment by SkyrilHD** [comment]
Do you have somewhere macOS installed? I don't think Windows can download the full installer...

**Comment by KenWuqianghao** [comment]
Oof, I don't. Maybe I can install Catalina then update it?

**Comment by SkyrilHD** [comment]
I found this you can try: https://www.reddit.com/r/hackintosh/comments/jrrhox/how_to_make_a_full_offline_installer_for_macos_on/?utm_medium=android_app&utm_source=share

Don't know if it works though

**Comment by KenWuqianghao** [comment]
Yeah, I've tried that, I stuck at the second step since the python file only supports ones below big sure.

**Comment by SkyrilHD** [comment]
That's fine... Catalina also works fine
