### ISSUE TITLE
No bootable device found

### ISSUE THREAD

**Issue by KenWuqianghao** [SkyrilHD/Dell-Exx50-Hackintosh#11]
I followed the guides completely and when I try to boot the laptop, it tells me "no notable device found"

**Comment by SkyrilHD** [comment]
> After the installation, mount the EFI partition of the installed OS and copy the EFI folder to its partition.

Did you do this?

**Comment by KenWuqianghao** [comment]
> > After the installation, mount the EFI partition of the installed OS and copy the EFI folder to its partition.
> 
> Did you do this?

Yeah I did

**Comment by SkyrilHD** [comment]
Check your boot order... Can you boot to the OS with USB?

**Comment by SkyrilHD** [comment]
Then make sure you placed the EFI correctly

**Comment by KenWuqianghao** [comment]
> Check your boot order... Can you boot to the OS with USB?

My boot order is right, opencore is on the top and I can't boot with USB, I'm still trying to get into installation

**Comment by SkyrilHD** [comment]
Check this diagram. ESP is the root of the USB Drive. If it still doesn't work, re download the EFI (it may be corrupted) and place it again
![IMG_20210420_184641_912](https://user-images.githubusercontent.com/28839925/115434568-22f7c280-a209-11eb-9121-477935f642ae.jpg)

**Comment by KenWuqianghao** [comment]
tbh I don't know what could possibly go wrong. The USB looks very good after following every step of the instruction. 
![Snip20210420_2](https://user-images.githubusercontent.com/20444505/115435030-b4673480-a209-11eb-90eb-a1dfabf75b4a.png)
![Snip20210420_3](https://user-images.githubusercontent.com/20444505/115435032-b5986180-a209-11eb-9330-428bf973f13c.png)

**Comment by SkyrilHD** [comment]
Go to your BIOS: System Configuration > USB Configuration, check if all three options are ticked. Also make sure you set your Boot sequence to UEFI and Secure boot to Disabled. Also try another USB port and boot via F12

**Comment by KenWuqianghao** [comment]
> Configuration

I just checked all of them are already set accordingly.
