### ISSUE TITLE
Installation interrupted

### ISSUE THREAD

**Issue by KenWuqianghao** [SkyrilHD/Dell-Exx50-Hackintosh#12]
I aborted my plan to install with a full installer and installed it during the daytime. I was able to boot into installation successfully but during the installation it restarts the laptop during the last 10 or 15 minutes of the installation and reboots into the installation page, meaning I have to restart again. This occurred 3 times already, what should I do?

**Comment by SkyrilHD** [comment]
@KenWuqianghao Make sure you formatted the drive as APFS and GUID partition table

**Comment by KenWuqianghao** [comment]
> @KenWuqianghao Make sure you formatted the drive as APFS and GUID partition table

Not Journal?

**Comment by SkyrilHD** [comment]
@KenWuqianghao Nope

**Comment by KenWuqianghao** [comment]
> @KenWuqianghao Nope

I formatted again, same thing.

**Comment by SkyrilHD** [comment]
@KenWuqianghao SATA Operation is set to AHCI in BIOS?

**Comment by KenWuqianghao** [comment]
> @KenWuqianghao SATA Operation is set to AHCI in BIOS?

Yep, AHCI

**Comment by SkyrilHD** [comment]
@KenWuqianghao Without logs I can't say much about it... Check the logs while you are installing. Iirc it was Window > Logs and set to Show all logs

Also it is normal to reboot, but instead of booting into the installer you need to boot to the SSD

**Comment by KenWuqianghao** [comment]
> @KenWuqianghao Without logs I can't say much about it... Check the logs while you are installing. Iirc it was Window > Logs and set to Show all logs
> 
> Also it is normal to reboot, but instead of booting into the installer you need to boot to the SSD

K I will do that. It just kept on restarting and clearing my progress on the installation.

**Comment by KenWuqianghao** [comment]
Alright, I found the issue, not a problem of EFI or anything related. Simply done incorrectly.
