### ISSUE TITLE
Unstable internet connection

### ISSUE THREAD

**Issue by KenWuqianghao** [SkyrilHD/Dell-Exx50-Hackintosh#14]
The internet connection is extremely unstable. I am sure the wifi is working well and this is an issue that didnt' occur when it was in windows. Is it fixable?

**Comment by SkyrilHD** [comment]
The next EFI update will get updated WiFi drivers. It is unstable because it doesn't work natively but rather needs to get ported which requires a lot of work. The new WiFi update should be more stable

**Comment by KenWuqianghao** [comment]
> The next EFI update will get updated WiFi drivers. It is unstable because it doesn't work natively but rather needs to get ported which requires a lot of work. The new WiFi update should be more stable

Alright, when would the next update come? I am very eager to use this hackintosh.

**Comment by SkyrilHD** [comment]
Next month maybe when OpenCore 0.6.9 gets released... Right now I am very busy with school, so it might get delayed

**Comment by SkyrilHD** [comment]
Intel WiFi should be more stable with the latest v1.4 release.
