### ISSUE TITLE
No internet connection with the newest EFI

### ISSUE THREAD

**Issue by KenWuqianghao** [SkyrilHD/Dell-Exx50-Hackintosh#17]
I didn't do any changes and airportlwlm is on.

**Comment by SkyrilHD** [comment]
Send output of `kextstat | grep 'AirportItlwm'`

**Comment by KenWuqianghao** [comment]
> Send output of `kextstat | grep 'AirportItlwm'`

Doing it right now.

**Comment by KenWuqianghao** [comment]
Alright, I put that line of code into the terminal and it tells me:
'Executing: /usr/bin/kmutil showloaded No variant specified, falling back to release'

Plus there's is this notification before I boot into opencore, maybe it is related
'No schema for ForceUefiSupport at 4 index, context<Quirks>'

**Comment by SkyrilHD** [comment]
Terminal says nothing else? Then it means AirportItlwm doesn't load. Can you check the top right of the keyboard if the wifi icon is lighten up

And oops instead of Forge I typed Force by mistake, that is definitely an issue I will fix in a few minutes

**Comment by KenWuqianghao** [comment]
The icon is on and the WiFi card is definitely working since I am using Ubuntu on the same laptop right now.

**Comment by SkyrilHD** [comment]
okay uploaded the fixed efi (1.5.2)...

idk about AirportItlwm really but I read that if you restart from Linux or Windows to macOS then it doesn't work but shutting down and booting straight to macOS fixes it 

https://github.com/OpenIntelWireless/itlwm/issues/131 that's the issue but that's apparently fixed so idk

Last thing I would suggest is to **replace** AirportItlwm with itlwm and use heliport to connect to the internet

**Comment by KenWuqianghao** [comment]
Hey man, I tried the newest EFI and booted straight to macOS, but no luck. Can you show me how to replace AirportItlwm with itlwm and use heliport to connect to the internet

**Comment by SkyrilHD** [comment]
What do you use for editing the config?

**Comment by KenWuqianghao** [comment]
VScode and Opencore Configurator

**Comment by SkyrilHD** [comment]
Here is a video on how to install itlwm (sry for low quality, I had to compress otherwise I can't upload to GitHub):

https://user-images.githubusercontent.com/28839925/117204647-de674c00-adf0-11eb-8e84-8fa452cf5020.mov

Basically I renamed AirportItlwm to itlwm.
Make sure Enabled is **true**!
Then copy itlwm to the kext folder

After that, download Heliport from here: https://github.com/OpenIntelWireless/HeliPort/releases and run the app

**Comment by KenWuqianghao** [comment]
I don't know why but for some reason it worked without doing any changes, but the connection is still unstable, don't know what's happening.
