### ISSUE TITLE
FaceTime and Imessenger 

### ISSUE THREAD

**Issue by gaslarfa** [SkyrilHD/Dell-Exx50-Hackintosh#18]
Hello friend, I would like to know if you manage to log in to Imessenger or FaceTime since every time I try to do it, it suddenly closes the session and I do not know why that happens

**Comment by SkyrilHD** [comment]
Last time I tried the serial number it worked fine. Try changing the serial number with genSMBIOS.

Here is a guide you can follow to fix iServices: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-macserial
