### ISSUE TITLE
This discussion about the E3550 models. 

### ISSUE THREAD

**Issue by pkombala** [SkyrilHD/Dell-Exx50-Hackintosh#19]
Latitude 3550 Only issue Mouse touch pad not working(please help me), audio make it id "3"working fine, Wifi Working fine (intel built in ),sleep done,

**Comment by SkyrilHD** [comment]
Which OS?

**Comment by pkombala** [comment]
Bigsure

**Comment by SkyrilHD** [comment]
Very weird... Do you have Windows on the machine? If so, can you check if it is an Alps Touchpad?

**Comment by pkombala** [comment]
> Very weird... Do you have Windows on the machine? If so, can you check if it is an Alps Touchpad?
Thanks for helping 
please try to find My trackpad brand name  

00:00.0 Host bridge: Intel Corporation Broadwell-U Host Bridge -OPI (rev 09)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
00:03.0 Audio device: Intel Corporation Broadwell-U Audio Controller (rev 09)
00:14.0 USB controller: Intel Corporation Wildcat Point-LP USB xHCI Controller (rev 03)
00:16.0 Communication controller: Intel Corporation Wildcat Point-LP MEI Controller #1 (rev 03)
00:1b.0 Audio device: Intel Corporation Wildcat Point-LP High Definition Audio Controller (rev 03)
00:1c.0 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #1 (rev e3)
00:1c.2 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #3 (rev e3)
00:1c.3 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #4 (rev e3)
00:1c.4 PCI bridge: Intel Corporation Wildcat Point-LP PCI Express Root Port #5 (rev e3)
00:1d.0 USB controller: Intel Corporation Wildcat Point-LP USB EHCI Controller (rev 03)
00:1f.0 ISA bridge: Intel Corporation Wildcat Point-LP LPC Controller (rev 03)
00:1f.2 SATA controller: Intel Corporation Wildcat Point-LP SATA Controller [AHCI Mode] (rev 03)
00:1f.3 SMBus: Intel Corporation Wildcat Point-LP SMBus Controller (rev 03)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)
03:00.0 Network controller: Intel Corporation Wireless 7265 (rev 59)

**Comment by SkyrilHD** [comment]
Hmmm doesn't say here... `dmesg | grep -i input` try with this command. Also I assume your Ethernet does not work either, as you have a Realtek Controller instead of Intel

**Comment by pkombala** [comment]
> Hmmm doesn't say here... `dmesg | grep -i input` try with this command. Also I assume your Ethernet does not work either, as you have a Realtek Controller instead of Intel

prakash@prakash-MS-7A71:~$ dmesg | grep -i input
[    0.395952] input: Lid Switch as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input0
[    0.396013] input: Power Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input1
[    0.396062] input: Sleep Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input2
[    0.396105] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input3
[    0.433960] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input4
[    1.965952] input: SynPS/2 Synaptics TouchPad as /devices/platform/i8042/serio1/input/input6
[    2.058313] input: PixArt Dell MS116 USB Optical Mouse as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/0003:413C:301A.0001/input/input7
[    2.058421] hid-generic 0003:413C:301A.0001: input,hidraw0: USB HID v1.11 Mouse [PixArt Dell MS116 USB Optical Mouse] on usb-0000:00:14.0-1/input0
[    7.038827] input: DELL Wireless hotkeys as /devices/virtual/input/input8
[    7.365921] input: Dell WMI hotkeys as /devices/platform/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/9DBB5994-A997-11DA-B012-B622A1EF5492/input/input9
[    8.255066] input: Integrated_Webcam_HD: Integrate as /devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1.8/1-1.8:1.0/input/input10
[    8.510951] snd_hda_codec_realtek hdaudioC1D0:    inputs:
[    8.560363] input: HDA Intel PCH Headphone Mic as /devices/pci0000:00/0000:00:1b.0/sound/card1/input11
[    8.726027] input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input12
[    8.786299] input: HDA Intel HDMI HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:03.0/sound/card0/input13
[    8.786390] input: HDA Intel HDMI HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:03.0/sound/card0/input14
[    8.786468] input: HDA Intel HDMI HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:03.0/sound/card0/input15
[    8.786550] input: HDA Intel HDMI HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:03.0/sound/card0/input16
[    8.786896] input: HDA Intel HDMI HDMI/DP,pcm=10 as /devices/pci0000:00/0000:00:03.0/sound/card0/input17
[   33.734634] rfkill: input handler disabled

**Comment by pkombala** [comment]
![Screen Shot 1442-11-10 at 7 27 49 PM](https://user-images.githubusercontent.com/65465364/122681591-a760c480-d1fd-11eb-89cb-bb3e837e1bef.png)
![Screen Shot 1442-11-10 at 7 28 01 PM](https://user-images.githubusercontent.com/65465364/122681593-a891f180-d1fd-11eb-9aa1-588d4f31efca.png)

**Comment by SkyrilHD** [comment]
And also disable VoodooPS2 R6. That's for Alps

**Comment by pkombala** [comment]
full working

**Comment by SkyrilHD** [comment]
Great! Will reopen the issue again until I update the README

**Comment by SkyrilHD** [comment]
For anyone who own a 3550 2015 model, need to do these changes to make a fully working Hackintosh:

### Remove
- IntelMausi.kext
- VoodooPS2Controller-R6.kext

### Add
- RealtekRTL8111.kext ([Download here](https://github.com/Mieze/RTL8111_driver_for_OS_X/releases))
- VoodooPS2Controller.kext ([Download here](https://github.com/acidanthera/VoodooPS2/releases))

### Config changes
- Update Kernel>Add by adding RealtekRTL8111 and VoodooPS2Controller and removing IntelMausi and VoodooPS2Controller-R6
   - Make sure to add VoodooPS2Controller with this order:
      - VoodooInput
      - VoodooPS2Controller
      - VoodooPS2Keyboard
      - VoodooPS2Trackpad
- change layout-id to "3"; The line you need to change: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/ae65a86a3ca7817ffbfb79d5637bad7431efb801/OpenCore/EFI/OC/config.plist#L414-L415

**Comment by pkombala** [comment]
One more small issue after sleep keyboard malfunctioning any help?

**Comment by SkyrilHD** [comment]
Since I don't use acidanthera's kext, I don't know

**Comment by pkombala** [comment]
acidanthera's kext, ?

**Comment by SkyrilHD** [comment]
https://github.com/acidanthera/VoodooPS2/releases

**Comment by ewddy** [comment]
a mi me da problemas de imagen cuando ya inicia la instalacion de pierde la imagen y queda todo borroso y no me deja hacer mas nada
