### ISSUE TITLE
E7450 Intel Wifi - Big Sur

### ISSUE THREAD

**Issue by shelterx** [SkyrilHD/Dell-Exx50-Hackintosh#20]
I can't for the life of it get wifi to connect. I tried both AirportItlwm and itlwm, they both see the wireless networks but complains that they can't connect because it needs the password. The password is correct so I don't know what's going on

I also tried connecting to iPhone 11 acting as hotspot, didn't work either.

Any ideas?

**Comment by SkyrilHD** [comment]
Can try using the Alpha Version? https://github.com/OpenIntelWireless/itlwm/releases

Also Hotspot doesn't work on AirportItlwm, due to missing AWDL functionality, so you need to use itlwm with the Heliport app. https://github.com/OpenIntelWireless/HeliPort/releases

**Comment by shelterx** [comment]
Nah, no luck at all.  The alpha version sees the networks but can't connect.

As for the iPhone 11 as hotspot, i saw it using AirportItlwm but it didn't show up in Heliport.

I also tired to connect to my 2.4Ghz network, same problem, it shows the WPA2 password prompt over and over.

Everything else seems to work tho'.

**Comment by SkyrilHD** [comment]
Sadly, nothing can be done on my end. I suggest creating a bug report on itlwm's repo (https://github.com/OpenIntelWireless/itlwm) with proper logs. [Link](https://openintelwireless.github.io/itlwm/Troubleshooting.html#getting-kext-logs-for-loading-failures) on how to gather logs.

**Comment by shelterx** [comment]
Just a quick note here...
I have the Intel Dual Band Wireless-AC 7260 card, 
According to this project the AC 7265 works, I thought the AC 7260 would work as well but not for me.

I asked the Airportitlvm devs snd the AC 7260 is supported so I don't know what's going on.
Perhaps the <string><string>pci8086,095a</string></string> needs to be changed to <string>pci8086,08b1</string> ?

**Comment by SkyrilHD** [comment]
Can you try that and see if there is some improvements?

Removing PciRoot(0x0)/Pci(0x1C,0x3)/Pci(0x0,0x0) should be enough

**Comment by shelterx** [comment]
Nah... nothing. itlwm connects if i turn wifi off and on in Heliport, it gets an IP and I see the wifi association in the router, then it just disconnects.

Airportitlwm doesn't connect at all, I also read that DHCP is broken in Big Sur using this driver?

**Comment by SkyrilHD** [comment]
Yeah DHCP is broken in Big Sur... But itlwm still should working normally. Maybe check your settings of the router. Afaik i.e. WAP3 does not work, 2,4GHz is unstable etc

**Comment by shelterx** [comment]
Ok, thanks for taking your time to respond. I'll fiddle some more but I think the problem lies in the macOS driver, other wifi devices I have works fine.
I'll try to submit some logs to the devs, not sure what logs they want tho'

**Comment by shelterx** [comment]
Btw, for some reason this won't work, I disabled the itlwm kext and SIP and allowed the extension:
```
cp -R itlwm.kext /tmp
sudo chown -R root:wheel /tmp/*.kext
sudo kextutil -v /tmp/*.kext
```

Quits with unspecified error?

**Comment by SkyrilHD** [comment]
I never got itlwm loading via Terminal, only via bootloader

**Comment by shelterx** [comment]
One last thing, I messed up, i was looking at the wrong machine, it's indeed an AC 7265 but it doesn't work, which's weird. BIOS issue, I have the latest?

Btw, it says on your page to change SMBIOS to MacBook8,1, I never did that, your supplied config got macbookpro12,1.
Is that correct or do I need to change SMBIOS?

**Comment by SkyrilHD** [comment]
The EFI should work as is, the only thing you need is to activate AirportItlwm. Which BIOS version are you on? Since you are able to search for networks, I don't think the WiFi card is disabled. So, it's a bit complicated.

MacBook8,1 is ONLY needed for 7350 which uses a Core M like the MacBook 2015. All other models should work just fine with MacBookPro12,1.

**Comment by shelterx** [comment]
Wifi is unblocked, I checked with rfkill in Linux. There are cases when it's blocked and you have to run rfkill unblock all.
I'm on bios A24.

Btw, i read that there might be a fix for DHCP for AirportItlwm on it's way..

**Comment by shelterx** [comment]
Downgraded BIOS, still the same problem.
I kind of know what's happening, wifi signals seems to die after initialization of the wifi device. it works for a split second then dies.
Something funky with the driver i think, could be a card revision problem.

**Comment by shelterx** [comment]
I swapped the Wireless NIC to an Intel Wireless AC 8260 instead, works fine now. 
I got one last question tho', how do i generate the ROM value? Every guide says to use the MAC address, but it doesn't work.
And the value in the config.plist isn't a MAC address.

**Comment by SkyrilHD** [comment]
First, you have to gather your Ethernet's MAC address by going into System Preferences > Network > 'Click on Ethernet' > Advanced > Hardware, and there should be your MAC Address (as an example I will use '5D:F6:U8:2Z:H4:K5'). Then, open your config.plist and go to PlatformInfo > Generic, enter your MAC Address into the ROM section (should be like this '5DF6U82ZH4K5') and you should be done.

**Comment by shelterx** [comment]
Might work if you have a plist editor, I used a text editor to edit the file. ;)
But I found out that you can just use [OpenCore Online Configurator](https://xieguozhong.github.io/opencoreConfiguratorOnline/#) to load/save the config.plist file.

Also, you should randomize the MAC-address but you should include the [apple vendor information](https://www.adminsub.net/mac-address-finder/apple)
So ECADB8 which's an apple MAC-address, becomes something like: ECADB8**112233**

**Comment by SkyrilHD** [comment]
Oh no, please don't use that. Download [PlistEdit Pro](https://www.fatcatsoftware.com/plisteditpro/) to modify the config.

I did not include Apple's MAC address but I just pasted my MAC address. As seen here: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#fixing-rom

**Comment by shelterx** [comment]
I actually just used it to get a proper MAC-address `<data>` to insert in the config.plist. But yes, a plist editor is the correct way to go.
Thanks for the help and support, keep up the good work. My E7450 is running like a champ now!
