### ISSUE TITLE
Bootable usb is not showing in boot menu

### ISSUE THREAD

**Issue by zainulhasan** [SkyrilHD/Dell-Exx50-Hackintosh#22]
Hello there,

I have Dell Latitude E7450. I want to install macOS on it. But bootable USB is not showing in the boot menu. I have tried 2 USBs with all the ports. The same USB is on Hp 450 G4.

Can anybody help regarding this issue?

Thanks

**Comment by SkyrilHD** [comment]
If you only have the EFI on the stick (meaning no installer), you have to format the drive as GPT with FAT32. However, if you do have the installer on the stick, mount the EFI partition and paste the EFI there.

**Comment by zainulhasan** [comment]
> If you only have the EFI on the stick (meaning no installer), you have to format the drive as GPT with FAT32. However, if you do have the installer on the stick, mount the EFI partition and paste the EFI there.

I created one USB using Olarila open-core image and replace EFI with your EFI and second using a mac and replace EFI with your EFI.n both cases USB is not showing in boot menu. I check after updating bios as well/ But not work

**Comment by SkyrilHD** [comment]
please use a vanilla installer (meaning no distros).

Follow this guide, it is pretty easy to understand: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/

**Comment by zainulhasan** [comment]
> please use a vanilla installer (meaning no distros).
> 
> Follow this guide, it is pretty easy to understand: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/

Thanks @SkyrilHD Boot issue has been resolved. N

**Comment by SkyrilHD** [comment]
Can you add `-v` to the boot args, so I can know where the problem is at?

https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/37b9c03278a191cb6a680b963cb4f9e145dfeb68/OpenCore/EFI/OC/config.plist#L1232-L1233

This is the line. It should be like this: `-wegnoegpu -v`

**Comment by zainulhasan** [comment]
@SkyrilHD,


![image](https://user-images.githubusercontent.com/10378868/126059853-197412f1-0713-4382-ae36-d4eea7313aa2.png)

**Comment by SkyrilHD** [comment]
Very weird never experienced this before

**Comment by zainulhasan** [comment]
> Very weird never experienced this before

@SkyrilHD Any lead or way to debug it ?

**Comment by SkyrilHD** [comment]
not that I know of since this is before any patches get applied. how did you install macOS, maybe that will help. is it via distro or vanilla?

**Comment by zainulhasan** [comment]
@SkyrilHD using this method
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/linux-install.html#downloading-macos

**Comment by SkyrilHD** [comment]
Can you double check your BIOS settings and maybe recreate the USB from scratch would help
