### ISSUE TITLE
Need USBMap for various Exx50 models

### ISSUE THREAD

**Issue by SkyrilHD** [SkyrilHD/Dell-Exx50-Hackintosh#28]
To prepare the Monterey EFI, we need to get rid of USBInjectAll, FakePCIID and FakePCIID_XHCIMux as they are broken on 11.3+. The recommended way is to enable USBMap which I created for E7250. Since USB mapping is very sensitive on different devices, we have to create USBMap for all models separately. As the only device I own is an E7250, I need a little help from you.

Basically, I want USBMap from [USBToolBox](https://github.com/USBToolBox/tool). I recommend doing this on Windows as it maps USB 2 and 3 automatically.

The tool is very easy to use:
- Open USBToolBox and in settings enable 'Use native classes'
- Go to 'Discover Ports'
- Plug a USB 3 device (if on macOS, a USB 2 and 3 device) into each port but keep in mind it has to detect in the tool (it will populate in green/blue)
- After plugging each device into the ports, go back and go to Select Ports (usually the default setting should be enough)
- Then build the kext by pressing the letter 'K' on the keyboard
- Upload kext and usb.json here

usb.json is needed for me in case there is an issue that needs to be fixed, which I can do from my end.

Exx50 model | USBMap available?
:----------: | :----------:
13 7350 | No
3550 2015 | No
E7450 | No
E7250 | Yes
E5550 | No
E5450 | No
E5250 | No
E3450 | No

**Comment by bobmanuk** [comment]
Map and KEXT for Dell E5450
https://drive.google.com/drive/folders/1G_mPCGZipTHhFma8unohqygRBEcIuLnv?usp=sharing

Plugged and unplugged usb 2 and 3 pen drive into the 3 USB ports on the laptop running Windows 10.

Hopefully its helpful.

**Comment by jogamer777** [comment]
> Map and KEXT for Dell E5450 https://drive.google.com/drive/folders/1G_mPCGZipTHhFma8unohqygRBEcIuLnv?usp=sharing
> 
> Plugged and unplugged usb 2 and 3 pen drive into the 3 USB ports on the laptop running Windows 10.
> 
> Hopefully its helpful.

@bobmanuk can you reupload the map please.

**Comment by bobmanuk** [comment]
I’m afraid this was from so long ago I no longer have the files or laptop, sorry

**Comment by HAKAP80** [comment]
The link below no longer work :( 

> Map and KEXT for Dell E5450 https://drive.google.com/drive/folders/1G_mPCGZipTHhFma8unohqygRBEcIuLnv?usp=sharing
