### ISSUE TITLE
iMessage and FaceTime

### ISSUE THREAD

**Issue by kapi3511** [SkyrilHD/Dell-Exx50-Hackintosh#31]
Hi! 
It's my first try with hackintosh. Everything is working well, except iMessage and FaceTime. I can't log in. Other Apple services like AppStore, iCloud work.
I am using AirportItlwm, is it why it don't work? Is it any fix for that?
![Zrzut ekranu 2021-10-28 o 16 42 10](https://user-images.githubusercontent.com/93334346/139279668-8831b0b3-b3eb-48a6-b6a4-0d742b172a56.png)

**Comment by SkyrilHD** [comment]
error disappeared means it's fixed?

**Comment by kapi3511** [comment]
No. The error disappeared and I still can't login.
I reinstalled macOS because of hash mismatch error, still the same problem with FaceTime and iMessage.
Before reinstall I changed serial in config.plist with that from smbios and set ROM value to my en0 Ethernet.

**Comment by SkyrilHD** [comment]
Did you reinstall with a full installer or online recovery?

**Comment by kapi3511** [comment]
Full offline installer, created on MacOS
