### ISSUE TITLE
bluetooth workaround

### ISSUE THREAD

**Issue by eggwhalefrog** [SkyrilHD/Dell-Exx50-Hackintosh#32]
Just wanted to share how to activate bluetooth again after turning it off:
`sudo killall bluetoothd`
Might be worth adding to the README

Credits: https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/295#issuecomment-954319930

**Comment by SkyrilHD** [comment]
Activating Bluetooth has been fixed in v2.1
