### ISSUE TITLE
Boot process taking abnormally long on e5450

### ISSUE THREAD

**Issue by kaem-e** [SkyrilHD/Dell-Exx50-Hackintosh#33]
Hi i was trying the latest release efi but it would spend an abnormally long ammount of time stuck on the apple logo (trying this on a e5450 w integrated graphics (enabling / disabling voodoo & intel wifi and Bluetooth kexts didn't seem to change much))

Coincidentally the efi linked [Here ](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/files/7397517/EFI.2.zip) seems to have fixed this (obviously no wifi or Bluetooth or touchscreen support (im using intel wifi) but it *did* boot into Monterrey recovery)

[Edit] i should also mention all bios settings are the same as mentioned in the readme

**Comment by SkyrilHD** [comment]
I pushed the change to master. Can you try it?

Also for debugging, add verbose mode to the boot-args, so it's easier to know what the issue is

**Comment by kaem-e** [comment]
Ill try it rn one minute

**Comment by kaem-e** [comment]
That seems to have worked, it did still take a bit to boot (roughly 5 minutes or so) but im guessing that's because its booting into recovery, 
![IMG_20211031_065841](https://user-images.githubusercontent.com/46230985/139563572-4467de4d-c41f-4a04-b904-53d52edc200a.jpg)


Ill try it with the voodooi2c and intel wifi & Bluetooth kexts enabled, tysm

**Comment by kaem-e** [comment]
Seems to be stuck after enabling those three, any ideas what may be causing this ? (Its been stuck here for the past 25 ish minutes ?)
![IMG_20211031_072153](https://user-images.githubusercontent.com/46230985/139564143-082be234-404b-42df-a425-2a047e6790bc.jpg)

**Comment by kaem-e** [comment]
Seems to just be stuck at this stage w verbose output enabled 
![Uploading IMG_20211031_074000.jpg…]()

**Comment by kaem-e** [comment]
Okay seems like the voodooi2c drivers were what was causing the trouble above, might be worth checking those out. It boots up fine after disabling those

**Comment by SkyrilHD** [comment]
`refusing new kext me.kisghorprins.VoodooInput, v1.1.1: already have prelinked v1.1.3` means VoodooInput is already loaded. This is VoodooInput from the new VoodooPS2 kext. Disable VoodooPS2 VoodooInput and enable VoodooI2C VoodooInput.

**Comment by kaem-e** [comment]
thank you so much, that fixed it
