### ISSUE TITLE
No HDMI Audio Output on macOS Monterey

### ISSUE THREAD

**Issue by quynkk** [SkyrilHD/Dell-Exx50-Hackintosh#34]
I have tested your OpenCore EFI after installed Monterey
All wifi, blt, QE/CI, ... almost work but when I plugged HDMI, I checked for audio (Both Control Center and System Preferences) and it show nothing expect Internal Output
![image](https://user-images.githubusercontent.com/90502232/139582990-656bb06e-d887-46c7-8c9a-7b804ca2c3be.png)
![image](https://user-images.githubusercontent.com/90502232/139582996-3ded279f-9f1e-4f1d-8d7b-b3cab9629b49.png)

**Comment by SkyrilHD** [comment]
It works on my E7250 just fine. What is the model of your laptop and did you try other HDMI cables/devices

**Comment by quynkk** [comment]
> It works on my E7250 just fine. What is the model of your laptop and did you try other HDMI cables/devices

I'm using E5550. I have changed both HDMI Cable and other TVs. 
HDMI Output hasn't shown.

**Comment by SkyrilHD** [comment]
You have a dGPU, right?

**Comment by kapi3511** [comment]
Is it any way to make hdmi audio work on Dell E5450 with Nvidia 830M? I don't want to make a new post, because this one in closed and I don't know if I can make a new one.

**Comment by SkyrilHD** [comment]
If HDMI is attached to the NVIDIA card, then no as NVIDIA is unsupported in macOS.

**Comment by kapi3511** [comment]
But HDMI is working, only audio is not working.
Also, I think it's attached to Intel because I had an Nvidia card disabled (with Device manager) while using Windows and everything was working.

**Comment by SkyrilHD** [comment]
Hmm okay. Can you post an IOreg one with HDMI connected and one without HDMI being connected?

**Comment by kapi3511** [comment]
![Zrzut ekranu 2021-11-6 o 00 27 42](https://user-images.githubusercontent.com/93334346/140588914-778ea728-1aa2-4f0b-8c6d-1a62d297a1a4.png)
Which one?

**Comment by kapi3511** [comment]
https://we.tl/t-DTskgXxO1r
https://we.tl/t-rdjhDI90ks
Is that it?

**Comment by SkyrilHD** [comment]
Thank you very much. I will check in a few days. School is currently screwing me over, so I have no free time.

**Comment by SkyrilHD** [comment]
Sorry, it already passed a month. Can you try this EFI?
[EFI.zip](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/files/7748113/EFI.zip)

CC @kapi3511 @quynkk

**Comment by kapi3511** [comment]
> Sorry, it already passed a month. Can you try this EFI? [EFI.zip](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/files/7748113/EFI.zip)
> 
> CC @kapi3511 @quynkk

Its not working.

Sorry, I'm just responding now. I stopped using MacOS because I had to run applications from Windows. GitHub did not send a message when I wrote it 3 weeks ago :/ 
![PXL_20220110_195506872 MP](https://user-images.githubusercontent.com/93334346/148830941-bcdc2940-3e48-46b9-8c4c-c662179ebdc7.jpg)

**Comment by SkyrilHD** [comment]
Follows this: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh#graphical-glitches-in-macos

**Comment by kapi3511** [comment]
It works. I had completely forgotten about it. Once macOS installs, I'll let you know if the HDMI audio works.

**Comment by SkyrilHD** [comment]
I didn’t add the fixes to the latest version. So, you need to try the EFI I sent here. But if you want I can add the fixes as well

**Comment by kapi3511** [comment]
On the EFI you sent here HDMI audio is working. The only thing that doesn't work is i can't change volume with a computer, but i don't know if it's MacOS thing (i didn't had any Mac)

**Comment by SkyrilHD** [comment]
@kapi3511 Pushed to master. You can try now with the latest commit.
