### ISSUE TITLE
Dell 3550 lid sleep issue

### ISSUE THREAD

**Issue by Miri-R** [SkyrilHD/Dell-Exx50-Hackintosh#35]
I would close the lid of the laptop but won't go to sleep but instead keep the display on until display timeout.
laptop won't wake up from sleep until I manually press the power button.
![Screen Shot 2021-10-31 at 11 34 46 AM](https://user-images.githubusercontent.com/58711480/139596922-de3bb046-7cca-4fd1-8a18-44eb7f47f02a.png)

anyways it works really good those are the issues im having

**Comment by SkyrilHD** [comment]
looks like the lid does not get detected at all. Could you upload an [IOReg](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip) please?

**Comment by Miri-R** [comment]
yep on it sorry its taking longer to upload on google drive then normally

**Comment by SkyrilHD** [comment]
you can upload here on GitHub as well

**Comment by Miri-R** [comment]
https://drive.google.com/file/d/16URjVbxL4e-r_rY4VhY9MteYaXuXs2VM/view?usp=sharing

**Comment by SkyrilHD** [comment]
You need to zip it first.

Looking at the IOReg, lid does get detected but your SMBIOS is `MacBookPro12,`. It should be `MacBookPro12,1` (you forgot the 1). Anything else looks almost the same as mine.

**Comment by Miri-R** [comment]
oh alrighty thanks for the help!
