### ISSUE TITLE
E5550 help

### ISSUE THREAD

**Issue by MazenAyman466** [SkyrilHD/Dell-Exx50-Hackintosh#36]
Good day,
I have a Dell Latitude E5550
I tried the latest EFI for monterey and for big sur. I even tried the 1.7 EFI and nothing seemed to work. 
I have a big sur usb drive with the efi mounted on it but all i get is the picker and nothing else. 
i can see the volume of my usb but when i try to launch it, it shows the apple logo then it reboots. 
any help would be appreciated

**Comment by SkyrilHD** [comment]
Enable verbose mode and send a picture before it restarts

**Comment by MazenAyman466** [comment]
One of my friend looked at the guide and he created a basic EFI idk what version it is but i works but major bugs. 
There is only wifi that is enabled and for some reason it isnt using heliport. 
I have so use of the keyboard, touchpad, bluetooth, sound, absolutely nothing except for wifi.
I have macOS Catalina and I can't seem to get any of your EFIs to work
The MAC partition simply doesn't show up in any of the EFI 
[Uploading EFI.zip…]()
![Screen Shot 2021-11-01 at 10 50 39 AM](https://user-images.githubusercontent.com/93510293/139647120-6464ea6f-4db6-4d68-a161-b5b71c98afc7.png)
![Screen Shot 2021-11-01 at 10 51 24 AM](https://user-images.githubusercontent.com/93510293/139647187-9813bd29-9b34-46df-9b2d-a7794826a599.png)
![Screen Shot 2021-11-01 at 10 51 40 AM](https://user-images.githubusercontent.com/93510293/139647225-c387c7db-acb1-4408-a322-70df9d97d71a.png)

**Comment by SkyrilHD** [comment]
Now since you have a working macOS, create a full installer and install it this way

**Comment by MazenAyman466** [comment]
Can you explain to me more that do you mean by that.

**Comment by SkyrilHD** [comment]
Yes

**Comment by MazenAyman466** [comment]
Okay will give that a shot

**Comment by MazenAyman466** [comment]
I have a big sur usb can i use that with the Monterey efi?

**Comment by SkyrilHD** [comment]
Yes, but you won't have WiFi unless you change it yourself

**Comment by MazenAyman466** [comment]
Is that with the help of heliport and activation of airport?

**Comment by SkyrilHD** [comment]
With this EFI this is not itlwm which needs Heliport but AirportItlwm which works natively

**Comment by MazenAyman466** [comment]
Great just waiting for the usb to finish the creation of the installer and will test it out.

**Comment by MazenAyman466** [comment]
I am in the recovery page installing big sur now and omg the mouse and keyboard are working. But i cant see any wifi option on the top right hand corner or there is no wifi option in what i am doing rn?

**Comment by SkyrilHD** [comment]
You need to enable AirportItlwm in the config

**Comment by MazenAyman466** [comment]
During the big sur recovery process the laptop restarted by itself at 3/4 of the way i thought that was normal. I waited and in the bootloader menu it showed the macos installer in the mac partition which is good. But now i have been stuck here for what seems like 30 minutes is this normal? ![image](https://user-images.githubusercontent.com/93510293/139660947-d5f034e3-c6f5-4579-b3d0-b544dd42fae9.jpeg)

**Comment by MazenAyman466** [comment]
Hey i got this and i am lost. 
![image](https://user-images.githubusercontent.com/93510293/139662590-b8db8afe-8ae5-49cc-8ec0-ba92b514c043.jpeg)

**Comment by SkyrilHD** [comment]
Select the bottom one

**Comment by MazenAyman466** [comment]
Omg thank you so much it is working now
What are the things i need to do now
![image](https://user-images.githubusercontent.com/93510293/139663145-c8269568-1cdc-4601-abca-86ab3e428863.jpeg)

**Comment by SkyrilHD** [comment]
Change the serial number with genSMBIOS and update to Monterey

**Comment by MazenAyman466** [comment]
How would i be able to update without wifi?

**Comment by SkyrilHD** [comment]
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/202dba6688a6312dbbae606f6e6b248138c16c40/OpenCore/EFI/OC/config.plist#L840

Set this to true

**Comment by MazenAyman466** [comment]
I did that and no wifi 
![image](https://user-images.githubusercontent.com/93510293/139664261-5bb009d5-36e2-4a2c-a2d1-20f13616a712.jpeg)![image](https://user-images.githubusercontent.com/93510293/139664312-3ff5eebb-af6d-478c-a796-078054fd7908.jpeg)

**Comment by MazenAyman466** [comment]
I cant use genSMBIOS since the wifi still isn't working.

**Comment by SkyrilHD** [comment]
`sudo kextstat | grep 'Itlwm'` type this terminal and check if you get any output. If yes, then it means AirportItlwm ist loading, else switch to itlwm + Heliport

**Comment by MazenAyman466** [comment]
Didnt work ill try to use heliport but before that should i close the line that i enabled?

**Comment by SkyrilHD** [comment]
It is easier to change it by changing the existing Airportitlwm line: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/master/OpenCore/EFI/OC/config.plist#L832-L849

Just replace `AirportItlwm` with `itlwm`

**Comment by MazenAyman466** [comment]
Without snapshot or anything right?

**Comment by SkyrilHD** [comment]
no need in this case

**Comment by MazenAyman466** [comment]
Thank you so much. 
Everything is great now. 
Just one last question what should i pick as the SMBIOS?

**Comment by SkyrilHD** [comment]
MacBookPro12,1

**Comment by MazenAyman466** [comment]
Thank you so much everything is working perfectly. 
You are a life saver.

**Comment by MazenAyman466** [comment]
Sorry i know that i am annoying but can i update the mac normally as if it was a real mac?

**Comment by SkyrilHD** [comment]
No worries. Yes you can update normally.

**Comment by MazenAyman466** [comment]
Thank you so much.

**Comment by MazenAyman466** [comment]
![image](https://user-images.githubusercontent.com/93510293/139901046-df403620-31fc-480e-ac02-428d175d955e.jpeg)

I keep getting this error every time i try to update. I re-downloaded the installer from the AppStore and still gives the same error

**Comment by SkyrilHD** [comment]
Can you update to v2.0 and try again?

**Comment by MazenAyman466** [comment]
Will do tomorrow since i am tired. But thank you so much again.

**Comment by MazenAyman466** [comment]
I tried the a couple efis and none seemed to work. 
I even tried to do a usb install but the usb doesnt show up in the boot menu.

**Comment by MazenAyman466** [comment]
Update: i got the usb to work but it doesnt show up in the boot menu to select the drive. Yet it shows up when i select the hardrive i have the big sur installation (main hard drive) and it opens the launcher but i am scared to update it that way, would it remove the efi that is in the main drive since the usb inst being read.

**Comment by SkyrilHD** [comment]
Very weird. I installed Monterey with the app AND with USB. Both worked fine. I never used it but can you try TINU? https://github.com/ITzTravelInTime/TINU

**Comment by MazenAyman466** [comment]
Am i doing the installation right?
Formatting the usb to gud partition then using the creating install media code to create it then 
--volume (my volume) then it asks for my password then y for formate and wait. 
After it is done i use mount efi on the usb and add the EFI. 
That is it right?

**Comment by SkyrilHD** [comment]
That's correct

**Comment by MazenAyman466** [comment]
Will anything happen if i used the efi built in the main hardrive and did an installation without formatting?

**Comment by SkyrilHD** [comment]
The EFI _should_ remain untouched unless you do a format. I never tried it.

**Comment by MazenAyman466** [comment]
Got it to work with my fingers crossed and the EFI file remained and everything is working fine and great.
![Screen Shot 2021-11-03 at 4 04 55 PM](https://user-images.githubusercontent.com/93510293/140075429-c396794b-ef94-4bf7-9ead-44cfae38f37d.png)
.

**Comment by MazenAyman466** [comment]
And when I was trying to test it and connect my airpods, I found out that the Bluetooths wasn't working at all.
![Screen Shot 2021-11-03 at 4 08 13 PM](https://user-images.githubusercontent.com/93510293/140075686-1143d63c-8038-45d4-a26a-a78017a69917.png)

**Comment by SkyrilHD** [comment]
Update the EFI to v2.0

**Comment by MazenAyman466** [comment]
just remove the old refi and add the new one?

**Comment by SkyrilHD** [comment]
Did you enable IntelBluetoothFirmware and BlueToolFixup?

**Comment by MazenAyman466** [comment]
I will try that now but what about the injector?

**Comment by SkyrilHD** [comment]
Injector got useless with Monterey, so now we use BlueToolFixup

**Comment by MazenAyman466** [comment]
it is working now but the trackpad buttons stopped working is that due to the kext being enables?

**Comment by SkyrilHD** [comment]
That should not happen. Hmm can you check on system preferences > trackpad if force touch is enabled. Of yes, disable it

**Comment by MazenAyman466** [comment]
Disabled it and nothing.

**Comment by SkyrilHD** [comment]
Buttons above or below trackpad?

**Comment by MazenAyman466** [comment]
Actually both are not working.

**Comment by SkyrilHD** [comment]
Ok this needs some investigation as the new kext was tested with my E7250 which only has a trackpad. So I did not implement any trackstick stuff (as it is my only device I can test).

**Comment by MazenAyman466** [comment]
That was odd i changed it the force click to off then added the old efi i had. Reboot. Downloaded the new efi v2.0. Changed the internet thing you told me reboot and it worked.

**Comment by SkyrilHD** [comment]
The old EFI has a very old PS2 kext which I decided to update and put it in the v2.0 EFI. As it is in beta a few bugs might happen

**Comment by MazenAyman466** [comment]
Oh okay got it. I just thought it was weird because i didnt change anything from the previous one.

**Comment by MazenAyman466** [comment]
Everything is working great right now and i am happy with everything. Just a question do i need to do anything for backup or as a just in case or last resort.

**Comment by SkyrilHD** [comment]
Backup for what exactly?

**Comment by MazenAyman466** [comment]
Sorry about the late reply. What i mean is that there is no chance that the efi file might get lost somehow because if then i would have no way to get the OS back and running.

**Comment by SkyrilHD** [comment]
You can't lose an EFI folder except maybe when you install Windows. But if you really want a backup, you can put the EFI folder inside a USB stick which is formatted FAT32 with GPT

**Comment by SkyrilHD** [comment]
Closing this issue as it is fixed but we can still chat here

**Comment by MazenAyman466** [comment]
Hey, i updated the EFI to the latest, did all the changed i did before like the smbios, the itlwm, bluetooth. It was pretty much identical. But now when i boot into the MacOS i never get passed the apple logo even in recovery mode

**Comment by MazenAyman466** [comment]
Got it working,i did as you instructed me before with the ITLWM and apparently that was the thing keeping it from booting up. The configs you already made are working and good. But just a warning that there was horizontal glitches after i did all that and the first way you had didn't work but the second did.

**Comment by tommasobab** [comment]
can you send me the catalina efi

**Comment by MazenAyman466** [comment]
Will give it a shot
