### ISSUE TITLE
Can't go to picker mode with press option key

### ISSUE THREAD

**Issue by catalinabigsur** [SkyrilHD/Dell-Exx50-Hackintosh#37]
Hi, I don't set any firmware password but when I go to Picker mode, I can't press Option key. Instead, I will press Command-R to go to Picker mode, which is Recovery. So how can I fix it?

**Comment by SkyrilHD** [comment]
Just hold down the command key

**Comment by catalinabigsur** [comment]
OK, it works. Thanks!
