### ISSUE TITLE
OpenCore 7.4 dont work in DEll E7450

### ISSUE THREAD

**Issue by gaslarfa** [SkyrilHD/Dell-Exx50-Hackintosh#39]
I tried to update from BigSur to Monterrei and it sent me this error.
Also try to Bootear BigSur but it does not load, it only shows the logo without the progress bar and it does not go from there

![WhatsApp Image 2021-11-03 at 08 05 24](https://user-images.githubusercontent.com/78608267/140057024-746a135d-9987-459d-b739-9e4f19468ae6.jpeg)

**Comment by SkyrilHD** [comment]
Did you enable FileVault?

**Comment by gaslarfa** [comment]
No, how do i activate it?

**Comment by SkyrilHD** [comment]
This EFI does not support FileVault. Don't enable it. Enable verbose mode and send a picture where it hangs

**Comment by SkyrilHD** [comment]
Which EFI version?

**Comment by gaslarfa** [comment]
0.7.4

**Comment by SkyrilHD** [comment]
There are two: v1.7 - Big Sur and v2.0 - Monterey

**Comment by gaslarfa** [comment]
Well then what do i do?

**Comment by SkyrilHD** [comment]
Update to master: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/archive/refs/heads/master.zip

This should fix the EXITBS:START issue.

**Comment by gaslarfa** [comment]
Same mistake
EXITBS:START

**Comment by SkyrilHD** [comment]
that's weird. can you boot to Monterey at least?

**Comment by gaslarfa** [comment]
This again
![WhatsApp Image 2021-11-03 at 08 05 24](https://user-images.githubusercontent.com/78608267/140069740-81add84c-5b84-4732-9dda-9c3c47988446.jpeg)

**Comment by SkyrilHD** [comment]
create a recovery stick

**Comment by gaslarfa** [comment]
How?

**Comment by SkyrilHD** [comment]
Here is the guide:
macOS: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html
Windows: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html
Linux: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/linux-install.html

**Comment by gaslarfa** [comment]
In that case I would have to format my disk drive with BIgSur
