### ISSUE TITLE
Brightness control not working

### ISSUE THREAD

**Issue by catalinabigsur** [SkyrilHD/Dell-Exx50-Hackintosh#43]

**Comment by catalinabigsur** [comment]
Hi, I have an issues when I boot Windows on OC. The brightness is not working, when I press f11/f12 it have a glitches about 5 seconds. I think you are not using Windows but can you fix it? Thanks

**Comment by SkyrilHD** [comment]
Installed Windows and it works on my end. I have no idea what it could be

**Comment by catalinabigsur** [comment]
Hi, here is the issue. The brightness control does not show up. And when I press multiply, it crash. @SkyrilHD

**Comment by catalinabigsur** [comment]
Uploading 65893776844__385F1783-0E35-485D-BF2B-E938141C3A1A.MOV…

**Comment by catalinabigsur** [comment]
https://drive.google.com/file/d/1i1_Nl9jFZjUvEDKgIrHLijSRdjNY_ws4/view?usp=drivesdk

**Comment by catalinabigsur** [comment]
https://drive.google.com/file/d/1i1_Nl9jFZjUvEDKgIrHLijSRdjNY_ws4/view?usp=drivesdk

**Comment by SkyrilHD** [comment]
Interesting... On Windows 10 it works fine. I will update to Windows 11 and check if the issue persists there. Does your laptop have a dGPU?

**Comment by catalinabigsur** [comment]
No, my Dell e7450 doesn’t have any dgpu

**Comment by SkyrilHD** [comment]
I just upgraded to Windows 11 and still no issues. My graphics driver is from 21.01.2020 with version number: 20.19.15.5126.

**Comment by catalinabigsur** [comment]
Did you use Refind to boot Windows?

**Comment by SkyrilHD** [comment]
No. Only OpenCore
