### ISSUE TITLE
E5250  airdrop not working

### ISSUE THREAD

**Issue by GithubFeed** [SkyrilHD/Dell-Exx50-Hackintosh#45]
Thanks to this EFI, I could run Mac monterey on my E5250.  Mostly works, except AirDrop. it can not find any nearby devices.

Intel Bluetooth firmware was enabled to use my Bluetooth keyboard and mouse.

Any suggestions to make the airdrop working?

If enable the IntelBluetoothInjector， Bluetooth will not work.

![35ED9076-2246-4E1D-9D36-434E948D5DBD](https://user-images.githubusercontent.com/43715502/153751948-be9853f3-2f4d-49e4-bf49-58cadac92aa8.jpeg)

**Comment by SkyrilHD** [comment]
AirDrop is a known issue that does not work on **all** Intel WiFi cards. If you want AirDrop, buy a Broadcom card from eBay.

![Screenshot_20220213-133102__01](https://user-images.githubusercontent.com/28839925/153753186-fe9af701-6656-468d-aade-76c0f8fc9bec.jpg)
