### ISSUE TITLE
Touchscreen does not work E5450

### ISSUE THREAD

**Issue by kaem-e** [SkyrilHD/Dell-Exx50-Hackintosh#46]
I followed the README.md files instructions to enable all voodooI2C kexts for touchscreen functionality but it does not seem to work 
![image](https://user-images.githubusercontent.com/46230985/157552791-9a0b7f44-407b-4dd7-8bd6-e90bfc783fbe.png)

**Comment by SkyrilHD** [comment]
Did you disable VoodooPS2's VoodooInput?

**Comment by SkyrilHD** [comment]
I assume you tried OpenCore 0.7.9. Can you try with the previous EFI version? https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/releases/tag/v2.4

I wonder if the new VoodooI2C update is broken.

**Comment by kaem-e** [comment]
just tried it it doesn't seem to work either

**Comment by SkyrilHD** [comment]
Hmm. Can you double check if touchscreen support is enabled in BIOS (if there is any). Since I don't have a touchscreen model, I cannot test what's wrong.

Can you send an [IOReg](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip) btw, so I can check if VoodooI2C is loading at all.

**Comment by kaem-e** [comment]
i dont think an option for enabling the touchscreen exists in the bios though i am certain it is enabled as i can easily use touh to move the cursor within the opencore boot menu (aswell as a dual booted linux install). Seems to be MacOS in specific that doesnt want to detect it, 

Here's the ioreg output ([github gist](https://gist.github.com/kaem-e/f7cb259be7891693437d062ff1ed1c84
))
[IOReg.txt](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/files/8233490/IOReg.txt)

**Comment by SkyrilHD** [comment]
I don't see any entry for I2C. Can you send an unmodified DSDT grabbed from Windows or Linux, e.g. SSDTTime. Also use the IORegistryExplorer I linked in the comment before.

**Comment by kaem-e** [comment]
yeah sure, here (github wasnt allowing me to upload the .ioreg and .aml files so i uploaded it to anonfiles) https://anonfiles.com/Fbeb49N7xa/Kaem_s_MacBook_Pro_2_ioreg
https://anonfiles.com/J2ha47N3xc/DSDT_aml
