### ISSUE TITLE
Dell E7450 WiFi Works But No Bluetooth

### ISSUE THREAD

**Issue by PieterAndriesBerg** [SkyrilHD/Dell-Exx50-Hackintosh#47]
How can I get bluetooth to work? I enable the airport.kext mentioned in the guide.

**Comment by SkyrilHD** [comment]
`Also, do not forget to enable IntelBluetoothFirmware and BlueToolFixup in the config to enable Bluetooth on Monterey!`

Did you enable those two kexts as well?

**Comment by PieterAndriesBerg** [comment]
ah thats the problem i think ill look at that tomorrow thanks for the tip :)

**Comment by PieterAndriesBerg** [comment]
Fixed! needed to enable kexts :)

**Comment by nty774** [comment]
No Bluetooth not work
Fixed! needed to enable kexts
