### ISSUE TITLE
E7450 no Monterey install option with Opencore 0.8.2

### ISSUE THREAD

**Issue by Vetrix68** [SkyrilHD/Dell-Exx50-Hackintosh#51]
I already had windows installed and all I can see is Windows option to select, no Monterey to install. When I use my old copy of Big Sur installer on Opencore version.... 0.7.7 i think..? I can see everything as I should.

**Comment by SkyrilHD** [comment]
Did you press the space bar to show the installer?

**Comment by Vetrix68** [comment]
Whoah I didn't expect that it is now hidden sorry
