### ISSUE TITLE
Trackpad doesnt show up E5450

### ISSUE THREAD

**Issue by kaem-e** [SkyrilHD/Dell-Exx50-Hackintosh#52]
the trackpad settings pane in system preferences doesnt seem to be able to detect the trackpad despite the trackpad itself working perfectly fine, gestures and all. 
![Screenshot 2022-08-09 at 8 51 03 AM](https://user-images.githubusercontent.com/46230985/183560251-51e8ce39-f181-4475-921e-ba79fd494ff8.png)

**Comment by SkyrilHD** [comment]
Does battery status work?

**Comment by kaem-e** [comment]
Yup though i have the battery removed atm from my laptop

**Comment by SkyrilHD** [comment]
Trackpad settings will not show if a battery is not connected. That's how Apple implemented it...

**Comment by kaem-e** [comment]
ahh, is there no way to force it or something perhaps by just making it think a battery is connected ?

**Comment by SkyrilHD** [comment]
unfortunately not that I know of...

However, you can change the trackpad settings in Terminal:
For example, if you want to enable Clicking, type this: `defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true`

Here is a list of properties you can change:
![image](https://user-images.githubusercontent.com/28839925/183563406-d364f924-85d9-4dda-9c10-34179ef3177d.png)


After you did your changes, you need to restart.

**Comment by kaem-e** [comment]
alright that seems to work well, thank you !
