### ISSUE TITLE
Ventura installer not opening

### ISSUE THREAD

**Issue by Vetrix68** [SkyrilHD/Dell-Exx50-Hackintosh#58]
This happens when i try to install Ventura on my Monterey hackintosh that is working perfectly.

![image](https://user-images.githubusercontent.com/75122363/199320409-ba791c4b-2644-456b-91f7-3220665f57f1.jpeg)

**Comment by SkyrilHD** [comment]
Did you use the Ventura EFI? Monterey EFI has no additional patches.

**Comment by Vetrix68** [comment]
> Did you use the Ventura EFI? Monterey EFI has no additional patches. 

Yes I did

**Comment by SkyrilHD** [comment]
How are you trying to update? OTA? Updating via full installer?

**Comment by Vetrix68** [comment]
Just fresh installer from pkg that i downloaded from method listed for MacOS in opencore guide

**Comment by SkyrilHD** [comment]
I used the released EFI without changing anything and it works for me... Can you try downloading the Install.app via App Store/Software Update?

![IMG_2529](https://user-images.githubusercontent.com/28839925/199350276-950ade14-8bcb-44cc-837f-de2ab8ba05f4.jpg)

**Comment by Vetrix68** [comment]
It's not compatible to download from App Store (e7450)

**Comment by SkyrilHD** [comment]
You have to download with the Ventura EFI (mentioned [here](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh#ota-from-monterey-to-ventura)). Monterey will still boot fine. If you need to download via WiFi, replace AirportItlwm from the Monterey one, otherwise you will have no WiFi.

I'll test the OTA process in a bit, but I tried clean installing Ventura on my second partition via install usb and it works. I think your installer is damaged.

**Comment by Vetrix68** [comment]
It installed and works but my windows option disappeared and every time I turn my laptop it shows an error message.

![image](https://user-images.githubusercontent.com/75122363/199508218-860779e9-5eda-476f-9a8a-fa0b371d8507.jpeg)

![image](https://user-images.githubusercontent.com/75122363/199508247-c3091ed1-85c5-44df-a4a9-24af3e917205.jpeg)

**Comment by SkyrilHD** [comment]
Hmm that’s weird, I can still choose Windows, mainly because I did not touch anything to it. Also does macOS output any 'Your computer was restarted because of a problem.'? If so, can you send me the log?

I have this when I use IntelBTPatcher. Might be in your case too.

**Comment by SkyrilHD** [comment]
About the restart issue: Like I assumed, IntelBTPatcher causes this issue. It’s out of scope of the EFI, I might do a bug report on the IntelBluetooth repo.

About Windows: Can you verify that you can boot to Windows with an older version of EFI? I will still double check what’s wrong.

**Comment by Vetrix68** [comment]
I will check that but I noticed text in the corner before system picker.

![image](https://user-images.githubusercontent.com/75122363/199528616-112c8cab-60b3-41e6-81a3-f0ee497f665e.jpeg)

**Comment by SkyrilHD** [comment]
You need to remove the entry from config.plist>NVRAM

reference: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/commit/6aa26145cdec6a6e7ff4feb3e624c726b9e52782

**Comment by Vetrix68** [comment]
That fixed that. I used the old EFI - Monterey idk what opencore version and Windows showed as it should.

![image](https://user-images.githubusercontent.com/75122363/199668989-194f8301-d711-4988-b436-1f34413a668b.jpeg)

**Comment by SkyrilHD** [comment]
Can you try like any v2.X EFI version.

I suggest: [v2.5](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/releases/tag/v2.5) and [v2.8](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/releases/tag/v2.8)

Or could you send the working EFI (remove serial number) and I'll take a look at it?

**Comment by Vetrix68** [comment]
I'm dumb. I made a stupid mistake and it works now. But should Ventura use much more of my CPU than Monterey? It's 100% usage for about 5 minutes after booting up. Monterey used much less of it (like 3%).

**Comment by SkyrilHD** [comment]
I think it is because of Spotlight indexing the drive, so it should be normal I guess.

Closing this issue…
