### ISSUE TITLE
Sleep/shutdown not working (E5250)

### ISSUE THREAD

**Issue by Richarito98** [SkyrilHD/Dell-Exx50-Hackintosh#60]
I tried USB Mapping but couldn’t figure out the issue.

**Comment by SkyrilHD** [comment]
OS? Any modifications to the EFI?

**Comment by Richarito98** [comment]
Solved. IntelBTPatcher caused the issue!

**Comment by SkyrilHD** [comment]
Yeah IntelBTPatcher is a bit buggy on Ventura. Glad you solved it!

**Comment by SkyrilHD** [comment]
Mentioned in README and v3.1 release that IntelBTPatcher is buggy on Ventura. Closing issue.
