### ISSUE TITLE
Single Tap/ mouse left click doesn't work sometimes after wake/ reboot

### ISSUE THREAD

**Issue by hect-dpr** [SkyrilHD/Dell-Exx50-Hackintosh#62]
Thanks for the EFI, updated to Ventura on Dell Latitude E7450, most things work well, except this weird issue. During the single tap/ mouse left click issue, right click, scroll, trackpoint all works and double tapping the trackpad behaves like a single tap 2 times out of 5. I'm using the latest release from your repo. Kindly help!

**Comment by SkyrilHD** [comment]
Trackpad issues were fixed a long time ago, I've never had a problem with my trackpad since. But I'll check again. Did Monterey have an issue with the trackpad as well?

**Comment by hect-dpr** [comment]
Hmm, It was working fine in Monterey. Not only the trackpad tap, click, even external mouse's left click doesn't work.

**Comment by Swearie** [comment]
Did you enable this option?

![image](https://user-images.githubusercontent.com/20731121/201427105-3b354ec6-e78b-42fe-9c4b-6e354be56436.png)

**Comment by hect-dpr** [comment]
Thanks @Swearie, surprisingly, enabling force click and haptic feedback on a normal dell trackpad seems to fix the random non working left click issue so far! Haven't faced the issue for a couple of days after a few sleep, reboot cycles! Any idea, why it should work though?

**Comment by hect-dpr** [comment]
The issue is back and random!

**Comment by Sprungles** [comment]
> The issue is back and random!

How did you update to Ventura, if I may ask? I had nothing but issues updating via OTA. But when I installed via a USB drive, everything worked perfectly.

**Comment by SkyrilHD** [comment]
Any update about this issue? Otherwise, I will close this issue in 2 weeks.

**Comment by Sprungles** [comment]
We discussed this over on Twitter. Feel free to close this issue.
