### ISSUE TITLE
E5450 restart after shutdown on Monterey

### ISSUE THREAD

**Issue by jamesle-0812** [SkyrilHD/Dell-Exx50-Hackintosh#64]
Hi, I'm on Monterey 12.6.3 with your build of v0.9.0. So I got some issues: Whenever I shutdown my hackintosh, it immediately reboot with a message of "your computer was restarted because of a problem" then boot into OS as normal. Similar thing happens when I restart the laptop or set it to sleep. Sometimes it works as it should, which shutdowns/restart properly. I did try to fix it by follow [https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html#fixing-shutdown-restart](url). Somehow it works, which makes the mac shutdown/restart properly more frequently, but the issue is still there. I also tried v0.8.5 and it still happens.
My setting is normal, enabled AirportItwm and IntelBluetooth kexts.
Can you make a double check please? Thanks in advance!

**Comment by SkyrilHD** [comment]
Can you try disabling IntelBTPatcher?

**Comment by jamesle-0812** [comment]
It seems fine by now. However, I read that IntelBTPatcher is required. So how I can use Bluetooth? Besides, the trackpad is a bit sensitive. When I swipe up to scroll down, sometime it automatically scroll up a little bit which is out of my expectation. How should I fix them?

**Comment by SkyrilHD** [comment]
Seems like the patches in IntelBTPatcher causes issues on our Intel WiFi, so it is best to disable the IntelBTPatcher kext.

As for the trackpad, I never had this issue since I transitioned to the 'new' VoodooInput kext. I know that there are issues with 3+ fingers but sadly it can't be fixed due to hardware limitations. However, 1 and 2 fingers should work without any issues.

**Comment by jamesle-0812** [comment]
I figured out that IntelBTPatcher is unnecessary when working with paired devices. It only affects when scan and pair to new devices, which makes sense when reading its description in [FAQ | OpenIntelWireless](https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-is-intelbtpatcher-trying-to-fix). 
Thanks for your helps.
