### ISSUE TITLE
Stuck after selecting boot device 

### ISSUE THREAD

**Issue by mian196** [SkyrilHD/Dell-Exx50-Hackintosh#66]
I copied all the efi folder to the usb and then i boot and i select the usb and then there's nothing there's a black screen for almost 5min then my laptop shutdown automatically

**Comment by SkyrilHD** [comment]
I need more information about:
- your Latitude model
- BIOS version
- EFI version
- list any changes you made from the downloaded EFI (e.g. enabled Intel Wi-Fi)
- macOS version you are trying boot
- is the USB drive USB 2 or USB 3
- have you reached the OpenCore boot picker after selecting the USB
- did you set the bios settings according to the guide/README

**Comment by mian196** [comment]
- Here is the info 
- Dell latitude E7450
- bios version A24(i update it to latest bios version)
- I'm currently on UEFI (I'm sorry I didn't get what is the EFI version )
- I didn't make any changes to downloaded efi
- I'm trying to boot mac os 11
- I have USB 3.0
- what do you mean by the OC picker ?
- yes i follow all the setttings in readme.
- 
-

**Comment by SkyrilHD** [comment]
> * I'm currently on UEFI (I'm sorry I didn't get what is the EFI version )

Do you use the [latest release](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/releases/tag/v3.2)?

> * I'm trying to boot mac os 11

Did you download the latest Monterey release?

> * what do you mean by the OC picker ?

The GUI to pick the installer. 
![](https://dortania.github.io/OpenCore-Post-Install/assets/img/gui.a10019ae.png)


Make sure, you placed the EFI correctly onto your flash drive. It should have this structure:

![](https://dortania.github.io/OpenCore-Install-Guide/assets/img/oc-structure.ed7eba0d.png)


Also make sure, you formatted the drive as FAT32 GPT if you are using an online installer.

**Comment by mian196** [comment]
yes, I use the latest EFI version. and I see that GUI but I got stuck after that and I don't have any vault.plist , vault.sig , nvram.plist, and opencore.txt .and USB is formated in gpt fat32

**Comment by SkyrilHD** [comment]
Is it a online or offline installer? Where did you get the installer from?

Add the verbose mode arg in the config.plist

**Comment by mian196** [comment]
it is the online installer i get it from open core macrecovery.py  and please can you explain what is the verbose mode arg im completely dumb in this

**Comment by SkyrilHD** [comment]
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/33f55522c38999fc90fcbc5015802dac8fa147d6/OpenCore/EFI/OC/config.plist#L1437

you need to add -v to this line (the last two arguments are not present in the Monterey EFI)

basically what it does, it enables Text mode after selecting the installer, so it is easier to debug the issue you have.

**Comment by mian196** [comment]
done adding -v but still there is no display :(

**Comment by SkyrilHD** [comment]
Usually there should be an icon of macOS, I assume the installer is broken and you need to redownload the installer again.

Follow the guide here: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html

**Comment by mian196** [comment]
I follow this guide and I tried mac os 11,12 and Catalina still has the same error I guess it won't work on my laptop .thanks for the help

**Comment by SkyrilHD** [comment]
Will check later when I'm at home. Do older releases work fine?

**Comment by mian196** [comment]
we really need a fix about this issue ;'(

**Comment by mian196** [comment]
> -v debug=0x100 keepsyms=1

i just used -v in verbose mode still nothing

**Comment by mian196** [comment]
> i tried 3.1, it gives me "OCB: LoadImage failed - unsupported" instead (of which i tried to fix by changing MinDate and MinVersion to -1 but it still threw the same error)

what version are you talking about?

**Comment by SkyrilHD** [comment]
Ok, so I downloaded a copy of Online Monterey installer and Online Big Sur installer, and I was able to boot to the installer just fine.

Keep in mind, you have to press the space bar to show more boot options and enter the installer, which has a gear icon on it. I don't know why there is an external drive icon in the first place, but yeah, entering the installer by booting via the gear icon works fine.

**Comment by mian196** [comment]
bro its booting up , but the problem is my resolution isn't good like i can't see anything when its boot int os online  installer

**Comment by SkyrilHD** [comment]
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh#graphical-glitches-in-macos

**Comment by mian196** [comment]
the error is in the online installer not in installed os i cant even use that tools to set my resolution that you mention in readme

**Comment by SkyrilHD** [comment]
The first method is done in the BIOS, as mentioned.

**Comment by mian196** [comment]
i did all the setting that you mentioned in bios section

**Comment by SkyrilHD** [comment]
> (Recommended) Enable 'Enable Legacy Option ROMs' in the BIOS by clicking General>Advanced Boot Options. [Here](https://supportkb.dell.com/img/ka02R000000oLv9QAE/ka02R000000oLv9QAE_en_US_2.jpeg) is a picture of that option.

Just do this.

**Comment by mian196** [comment]
let me try it also

**Comment by mian196** [comment]
thanks, bro for helping me out. so the summary of errors I got and how to fix it

- first apply the bios settings given in the readme
- then turn on legacy rooms in bios (also given in readme)
- boot the USB and press space bar (its must )
then done . thanks for solution @SkyrilHD and @quxngeh  you can do the same I did

**Comment by mian196** [comment]
sorry for taking your time again . but after installing the mac os i stuck into boot loops is there any way to fix it. thanks in advance

**Comment by SkyrilHD** [comment]
Sorry, but can you provide any logs? Also, were you able to boot to macOS before? What do you mean by boot loop? Add -v in boot-args.

**Comment by SkyrilHD** [comment]
Check if you did format the drive correctly, it should be APFS and GUID partition table.
