### ISSUE TITLE
Dell Latitude E5550 Losses Connection After Wake From Sleep

### ISSUE THREAD

**Issue by Bill-Joe-Tech** [SkyrilHD/Dell-Exx50-Hackintosh#69]
As the title suggests, the Wi-Fi connection is lost after wake up from sleep. This occurred after opening the laptop lid from sleep. Temporary fix is to restart.

**Comment by SkyrilHD** [comment]
OS version? Also, I suggest updating the AirportItlwm kext to the latest alpha version. It may include some fixes.

**Comment by Bill-Joe-Tech** [comment]
I'm not sure if I am able to recreate the issue, however it does take a good 2-4 minutes to connect back to WiFi from sleep mode. Is this normal with Hackintoshes?

**Comment by SkyrilHD** [comment]
Please test the latest release. I couldn't reproduce your issue.
