### ISSUE TITLE
Latitude E5550, installer not booting

### ISSUE THREAD

**Issue by KzoroxR** [SkyrilHD/Dell-Exx50-Hackintosh#70]
Hello, 

I'm having some trouble booting the **macOS Ventura** installer on my **E5550**.
Here's the problem I'm having and the things I've been able to try:

My first attempt was with version 3.2 Ventura and an online installer downloaded with macrecovery.py. 
I took care to place my EFI folder as well as my folder containing the recovery at the root of my USB.
I also took care to set my **BIOS to the recommended parameters**.

I then booted my USB and found myself on the screen with the choice of Windows or my USB and I press the space bar to **bring up the gear** and press enter to boot.

Just after that.. **nothing** a black screen for very long minutes, and my keyboard lighting up by itself from time to time.

I also **tried adding -v to my config.plist** to get more infos and... Nothing at all, **a black screen**.

I've tested **other USB keys : same problem**.

I tested with Ventura version 3.0, same thing.
I also tested version 3.0 Monterey and a Monterey recovery : no result.

I've been trying for a while (it's been like two weeks I'm on it 🥲) and now I think I need to ask for help, as I've been browsing the various topics here for far too long looking for my miracle solution!

Thank you in advance for your help !

**Comment by SkyrilHD** [comment]
Can you try disabling ProvideConsoleGop?

https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/master/OpenCore/EFI/OC/config.plist#L1753-L1754

**Comment by KzoroxR** [comment]
Hi there,

Well, it boots in console-like mode but still nothing..

Here is a video of what I've got : 
https://photos.app.goo.gl/pbjkAqKowY2SphSH6

NO NAME is my USB, and RECOVMAC is a partition on my disk (I tried a lot of things yeah..) and both are doing the same thing

**Comment by SkyrilHD** [comment]
I noticed there are config errors in the beginning, the config does not match or is broken. Re-download the latest release of the EFI and try booting the installer without doing any changes.

The EFI is definitely working as I used it to boot Sonoma and it works.

Another thing I suggest doing is to reset the NVRAM, reset the BIOS settings to default and after that setting the recommended BIOS settings according to the README: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh#recommended-bios-settings

Also for online recovery, make sure to format the USB correctly: GUID Partition Table, FAT32

I will try to boot to Ventura as well.

**Comment by SkyrilHD** [comment]
Works here:

![IMG_4989](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/assets/28839925/07df7360-4d39-41f9-b811-da75292ca363)
![IMG_4990](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/assets/28839925/972ef2d1-f339-4a96-951c-27088f489a89)

**Comment by KzoroxR** [comment]
Woah thanks, I tried these a tons of time, redownloaded everything and so on.. but it seems that resetting NVRAM plus resetting BIOS default setting right after changed something this time !

![Snapchat-538979778](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/assets/49638816/5fb5caaa-cb06-41c0-b3c6-826ff3a92b95)

Now my question is, is there a way to enable Intel Wifi to download Ventura or should I use ethernet instead ?

**Comment by SkyrilHD** [comment]
For stability and speed, use Ethernet, otherwise you can use Wi-Fi as well.

Set this to true for Wi-Fi:
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/33f55522c38999fc90fcbc5015802dac8fa147d6/OpenCore/EFI/OC/config.plist#L886

For Bluetooth, enable these kexts:
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/33f55522c38999fc90fcbc5015802dac8fa147d6/OpenCore/EFI/OC/config.plist#L904
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/33f55522c38999fc90fcbc5015802dac8fa147d6/OpenCore/EFI/OC/config.plist#L940

**Comment by KzoroxR** [comment]
Hmm tried with Ethernet but got this..

![Snapchat-867864387](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/assets/49638816/00023fdb-9e29-4746-81ef-d9db2e50344f)

This computer seems not wanting macOS at all 😅

**Comment by SkyrilHD** [comment]
Hmm, can you try changing the SMBIOS (+ Serial, etc.) to MacBookPro14,1? Maybe it is due to the unsupported SMBIOS we use.

Did you also create a macOS partition on the internal drive?

**Comment by KzoroxR** [comment]
Never changed the SMBIOS before, is it something to change in the config.plist ?

Yeah I created a partition for macOS named OS and configured properly (at least I think it is)

**Comment by SkyrilHD** [comment]
Yes, you need to change these lines:
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/33f55522c38999fc90fcbc5015802dac8fa147d6/OpenCore/EFI/OC/config.plist#L1502-L1524

Here is a little video you can watch on how to change the SMBIOS:
https://github.com/SkyrilHD/HP-8x70W-Hackintosh#generating-your-own-serial-and-editing-rom

**Comment by KzoroxR** [comment]
Seems to work perfectly! 

![Snapchat-1268219906~2](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/assets/49638816/795de632-3e93-409c-9026-c8dfc91e835b)

Unless big performance issues but I assume it is something normal?

**Comment by SkyrilHD** [comment]
There is a performance issue due to missing GPU acceleration.

Follow the readme to install it back: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh#gpu-acceleration-on-ventura

**Comment by KzoroxR** [comment]
Yeah I definitively should read this README entirely..
That works perfectly, this is awesome.
Thank you again!! 🙏🏻

**Comment by SkyrilHD** [comment]
Glad to hear that! Will close the issue as it works.

**Comment by MazenAyman466** [comment]
@KzoroxR could you send me the efi file and try it out since i have the exact same issue but doing the fixes that were written here nothing worked out
