### ISSUE TITLE
Dell Latitude E7450 Macos Ventura OCLP patch error 71

### ISSUE THREAD

**Issue by klswar0** [SkyrilHD/Dell-Exx50-Hackintosh#71]
Hi
I'm having trouble patching my e7450 on ventura.
When I try to patch my macOS with an older opencore patch, it says "Unable to build a new kernel cache" (the rest can be seen in the picture). 
I tried:
-clean install
-OTA from Monterey
-older version of efi and OCLP (because I managed to patch it some time ago )
-disabling wifi

picture   https://mega.nz/file/zDADURhZ#YA0mTfrXCCnfP5wvU_qbDvFsvzCWQXr8udeGePR-Yuw

verbose boot (This is the end that repeats itself endlessly) https://mega.nz/file/LXpESLYD#8SlCaODHipAJc_05gqmzmH1EIOsO4UWWPzR0vj4NK7o

Sorry for my bad english 
thanks

**Comment by SkyrilHD** [comment]
Which version of Ventura are you trying to run OCLP on? Also, which version of OCLP and EFI are you using?

**Comment by SkyrilHD** [comment]
Please test with the latest release again.
