### ISSUE TITLE
Dell E5550 working fine 😀🔥

### ISSUE THREAD

**Issue by tommasobab** [SkyrilHD/Dell-Exx50-Hackintosh#73]
Hi, so i followed the guide, downloaded the installer on the Dortania guide, copied the efi folder but when i boot in to the usb compares the apple logo and it stuck on it

**Comment by tommasobab** [comment]
Actually is working everything fine so you can add this model to the working ones 👍
![Schermata 2023-08-18 alle 18 24 19](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/assets/142430512/70b32252-7bd5-4738-9d4b-30ab5e1dd5cd)

**Comment by Bill-Joe-Tech** [comment]
Interesting. I was unable to get Bluetooth and my SD card working. Have you had these same issues?
