### ISSUE TITLE
Hackintosh on the E5450 Latitude.

### ISSUE THREAD

**Issue by hackitosh2323** [SkyrilHD/Dell-Exx50-Hackintosh#74]
The version of Opencore 0.9.5 doesn't work with the wifi cards the Dell Latitude E5450 so if you would like wifi working you can use the Opencore version 0.8.5 but can you still try to fix it on the latest version.

**Comment by SkyrilHD** [comment]
Which OS are you using?

**Comment by SkyrilHD** [comment]
Just downloaded the EFI and it works completely fine. Make sure you did not download the Ventura EFI by accident. Re-download the EFI from the releases in case the download was broken. Double-check if you enabled AirportItlwm, IntelBluetoothFirmware and BlueToolFixup in the config.plist. If you still do not have Wi-Fi, replace AirportItlwm with itlwm and use HeliPort instead.
![Bildschirmfoto 2023-09-19 um 17 08 00](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/assets/28839925/79fa2407-4a53-43dc-ba5e-6a17532128d3)

**Comment by hackitosh2323** [comment]
Ok, maybe it doesn't work with my machine since its refurbished but thank you for clearing this issue with me, just wanted to double check. Really thank you.

**Comment by hackitosh2323** [comment]
Im not sure, how do I check it?

**Comment by SkyrilHD** [comment]
Use Hackintool

**Comment by hackitosh2323** [comment]
Where to see it, I have Hackintool but I'm not able to find it?
![Screenshot 2023-09-19 at 18 27 19](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/assets/145181161/18ba4d53-69dc-4621-9904-9f9403859d0f)

**Comment by SkyrilHD** [comment]
Go to Peripherals

**Comment by hackitosh2323** [comment]
It says Wireless 7265

**Comment by SkyrilHD** [comment]
Try switching to itlwm then

**Comment by SkyrilHD** [comment]
Yes

**Comment by hackitosh2323** [comment]
Hey do I update the efi from the website or hackintool

**Comment by SkyrilHD** [comment]
Sorry, i don’t know what you mean

**Comment by hackitosh2323** [comment]
So do I basically update the efi from your efi or the hackintools efi

**Comment by SkyrilHD** [comment]
You just take the OpenCore 0.9.5 EFI and replace AirportItlwm with itlwm. Don't forget to change it in the config too.
