### ISSUE TITLE
E5550 installer not showing

### ISSUE THREAD

**Issue by MazenAyman466** [SkyrilHD/Dell-Exx50-Hackintosh#75]
Hey! I used your help before and everything was going great until i had to get a new hard drive since the old one died on me. 
So got everything to go smooth, read the issue post we had and followed it reached into the installer and everything was smooth. Then poof it just came blank. Nothing seemed to work anymore. And everytime i open into the open core file on the boot menu i just see my windows partition and the efi file. Read every article there is here and tried alot but nothing seemed to work. I reinstalled Ventura. Using the latest ventura efi 3.3 using it as a fresh download and also disabling all the things that you said, with resetting of nvram. And all i get is just a blank screen. 
Couldnt find my old usb that i had working since i moved. So now i am stuck back to square one. A windows laptop and a non bootable usb. So any like idea what would be the issue. 
E5550
Thanks in advance.

**Comment by MazenAyman466** [comment]
Used a new drive and added the DMG file using balena etcher then added the latest ventura efi file and it opens up just like before showing only 2 things to choose from
1 efi
2 windows
When i choose the efi it is just a black screen and nothing else and after around 3 mins or so it reboots into the opencore menu again. 
Resetting the bios to default then reset nvram and vise versa with the bios config changes and nothing seemed to work.

**Comment by SkyrilHD** [comment]
Can you try to format the drive as GPT and FAT32 and put the EFI directly to the drive (no need to mount the EFI partition). This should get OpenCore booting just fine. Now, I would try to create an online installer by following this guide: [Link](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html)

The thumb drive should look like this at the end: 
![](https://dortania.github.io/OpenCore-Install-Guide/assets/img/com-efi-done.a6fb730e.png)

There is a possibility that the online installer won't show up, you need to press the space bar as recovery dmgs are hidden by default

**Comment by MazenAyman466** [comment]
Well after some digging and diving into the guide, made a fresh recovery dmg and with the latest efi it worked but no wifi to download it. Enables airport and it showed up but every time i try to connect to it, it just reboots. Any ideas?

**Comment by SkyrilHD** [comment]
Latest EFI as in Ventura or Sonoma? If you try to enable Wi-Fi on Ventura with the Sonoma EFI (and vice versa), there will be a mismatch, and it won't work.

**Comment by MazenAyman466** [comment]
Latest Ventura on the ventura recovery

**Comment by SkyrilHD** [comment]
Can you try downloading the latest version of AirportItlwm https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0-alpha

**Comment by MazenAyman466** [comment]
With snapchat or no?

**Comment by SkyrilHD** [comment]
No need to snapshot as long as you enabled AirportItlwm in the config, replacing the kext is enough

**Comment by MazenAyman466** [comment]
Same thing

**Comment by SkyrilHD** [comment]
Interesting, I never had this issue before... Can you try to use Ethernet for the installation?

**Comment by MazenAyman466** [comment]
Sure will try

**Comment by MazenAyman466** [comment]
Problem is, i need the wifi too so any idea of any fixups or so that i can do if it installed?

**Comment by SkyrilHD** [comment]
It is better to do it in Post-Install, since the recovery is very limited.

**Comment by MazenAyman466** [comment]
Nope didnt work either with ethernet

**Comment by SkyrilHD** [comment]
that's weird, does safari work?

**Comment by MazenAyman466** [comment]
No it doesnt. Nothing does which is also weird.

**Comment by MazenAyman466** [comment]
Just to make sure, there is no need to enable all the intelfixups? Or specific ones. Correct?

**Comment by SkyrilHD** [comment]
For WiFi, it is enough to enable just AirportItlwm
IntelBluetoothFirmware, IntelBTPatcher and BlueToolFixup are for Bluetooth
Ethernet should work OOTB

Can you try resetting the BIOS settings and NVRAM again?

**Comment by SkyrilHD** [comment]
Can you try connecting to your phone's hotspot?

**Comment by MazenAyman466** [comment]
Did that too and nothing

**Comment by MazenAyman466** [comment]
Trued the 3.2 efi, didnt work, the 3.1 also didnt work. And now trying the 3.3 again and will try removing airport and just download the latest version of itlwm and adding it into the config.plist and see how that one works since it worked the first time you helped me but that was after the installation.

**Comment by SkyrilHD** [comment]
FYI, you can try adding your WiFi SSID and password inside the Info.plist of itlwm.kext. Use a plist editor and go to IOKitPersonalities>itlwm>WiFiConfig>WiFi_1

This is necessary since you can't use the Heliport app inside recovery.

<img width="529" alt="image" src="https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/assets/28839925/880b280c-aa84-4558-93be-cce10edb9f92">

**Comment by MazenAyman466** [comment]
Nothing at all

**Comment by SkyrilHD** [comment]
which WiFi card do you have in your system? Check in Windows

**Comment by MazenAyman466** [comment]
Ps. Got an offline installer here next to me in a different usb and the problem with that one is that the .dmg wont even show up.

**Comment by SkyrilHD** [comment]
I think the offline installer is damaged and hence it won't show up in OpenCore

**Comment by MazenAyman466** [comment]
Dual-band wireless-ac 7265NGW

**Comment by SkyrilHD** [comment]
Can you remove these lines from the config: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/commit/90023718c5f120cddf44c406fe7467d5043a1842

**Comment by MazenAyman466** [comment]
And continue with itlwm or airport?

**Comment by SkyrilHD** [comment]
would try with airportitlwm first, then itlwm

**Comment by MazenAyman466** [comment]
Exact same thing with both only this time the itlwm just didnt get into the recovery page at all. All it did was reach into the apple logo and just wait for a while and then resets. While airport did exactly the same thing when connecting. 
Btw i got a PKG file from ventura and i have it on usb. The thing it i dont exactly know how to put it on a usb with the efi, it is just a simple copy from the os itself. I got that and the damaged dmg. So any idea on how i can use the pkg?

**Comment by SkyrilHD** [comment]
For pkg, you need macOS since it has to be installed

**Comment by MazenAyman466** [comment]
Okay so downloaded 3 different versions of each Sonoma and Ventura. With being extra careful to use the correct efi for each and somehow every single one of them all isnt appearing on the boot menu, i even got 2 usbs that i created from a mac using the the install app on the mac from the app store and still nothing showing up. Maybe there is something i am missing? Any ideas?

**Comment by MazenAyman466** [comment]
Redownloaded the absolute latest sonoma version and now when i select the usb from the boot menu, i cant see anything only the reset nvram, openshell and toggle sip

**Comment by MazenAyman466** [comment]
Monterey worked with the latest 4.0 efi in recovery, and it loaded and everything. So if i somehow wanted to switch now to sonoma how would i go about that?

**Comment by SkyrilHD** [comment]
I would install Monterey first, then download a copy of Sonoma from the App Store. With that, I would create a USB installer, so there is an offline installer. I would have created a second partition on the drive and installed Sonoma on that. So in case something goes wrong, I would still have a bootable OS

**Comment by MazenAyman466** [comment]
Will give it a shot already downloading Sonoma

**Comment by MazenAyman466** [comment]
After downloading it and everything during the installation it is saying that it is not supported

**Comment by SkyrilHD** [comment]
Closing this issue as it is now outdated.
