### ISSUE TITLE
E5450 installer stuck

### ISSUE THREAD

**Issue by ViBE-HU** [SkyrilHD/Dell-Exx50-Hackintosh#77]
about 1,5 year ago i tried to create my opencore installer for my E5450. but i was a noob (and still) and while it mostly worked it was far from perfect and i did not manage out the issues. so i cancelled the project.

but a few days ago i decided to create a new ventura build for my hp prodesk 400 g3 dm. it is kaby lake based and i thought it might be way more easier but sadly i instantly stuck with it before system booting. it really bugs me so i try to fix it hopelessly.

meanwhile of the struggling i found your repo and decided to give another shot for my E5450. your config looks very detailed and well made but it wont started the installer for some reason. i had to switch off `HideAuxiliary` and then choose .dmg. and i also added my recently made fake hardware ID. after this the installer started properly and looks like i have internet connection too. BUT when the installer starts it says that it cannot download some files and i should try later. i'm using your ventura config with the ventura recovery image.

**Comment by SkyrilHD** [comment]
You won't see .dmg installers by default, pressing the space bar shows all auxiliary boot options (this also includes .dmg installers). Make sure you enabled AirportItlwm in the config.

**Comment by mian196** [comment]
Well i tried lots of things also before but i will tell you a simple solution. First goto oralila website then goto vanilla images download the image you want (in my case i tested 11,12 and 13) after download the image follow the instructions there burn the image to usb using balena etcher then mount the efi partition on usb ( you can follow the guide on web) but last step is EFI folder Don't put the folder they gave you download the boot zip file from here like i choose venture then put it in efi partition then you ready to go just boot it up

**Comment by ViBE-HU** [comment]
> You won't see .dmg installers by default, pressing the space bar shows all auxiliary boot options (this also includes .dmg installers). Make sure you enabled AirportItlwm in the config.

i guess you misunderstood me. via lan the laptop connects. safari can reach the net. of course i tried via wifi too but no luck:

![IMG20231224185327](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/assets/640109/f1e31bc3-59f7-4751-b4b9-193e076f161c)

**Comment by SkyrilHD** [comment]
I suggest you create an offline installer with this tool: https://github.com/corpnewt/UnPlugged

**Comment by ViBE-HU** [comment]
> I suggest you create an offline installer with this tool: https://github.com/corpnewt/UnPlugged

meanwhile i did some research. as i understand this is compatibility issue. broadwell is not supported by ventura and that is the main issue. i mean it is not important for me to install the latest macos on an unsupported platform. my goal is to get a working one on the corrent one. maybe the reported issues is still an issue but monterey on this machine is fine for me. now i'm checking your monterey build.
