### ISSUE TITLE
Wifi not working on 14.5 - Broadcom Wifi Card

### ISSUE THREAD

**Issue by johannameoww** [SkyrilHD/Dell-Exx50-Hackintosh#79]
Apple removed the drivers for Broadcom Wifi Cards. I'm not quite clever enough to readd the driver - is it possible to readd the driver in a new version?

**Comment by SkyrilHD** [comment]
Check here to enable Broadcom WiFi cards on Sonoma: https://github.com/5T33Z0/OC-Little-Translated/blob/main/14_OCLP_Wintel/Enable_Features/WiFi_Sonoma.md

**Comment by johannameoww** [comment]
Thank you, this tutorial finally worked.

**Comment by SkyrilHD** [comment]
Closing as the issue has been resolved.
