### ISSUE TITLE
No internet connection when installing

### ISSUE THREAD

**Issue by KenWuqianghao** [SkyrilHD/Dell-Exx50-Hackintosh#8]
I created a recovery usb stick and when trying to install I have no way to connect to the internet. No wifi icon on the top right corner. I'm using an E7450. Do I need to replace the wifi card?

**Comment by SkyrilHD** [comment]
I assume you have the stock Intel Card. Did you enable AirportItlwm in the config? This is the line you need to set to true: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/ddd8a6bf40cab1762a3b3061ff2ae5a32e49d1ce/OpenCore/EFI/OC/config.plist#L836

**Comment by KenWuqianghao** [comment]
Thank you so much! It is working now!
