### ISSUE TITLE
Open Core Boot Menu show seconds then a black screen apear

### ISSUE THREAD

**Issue by EliasWss** [SkyrilHD/Dell-Exx50-Hackintosh#83]
i downloaded the efi and the macOS recovery dmg they i putted the two recovery files inside `com.apple.recovery.boot` folder in root and the efi folder in root but once the boot menu of open core wich contain the installer and reset nvram apear it become black after seconds oh and the open core is menu look old its not same as the one apearing for my descktop made by me

**Comment by SkyrilHD** [comment]
There is a five second timer, if you don't move the picker, it will automatically boot to the selected option. For the black screen issue, can you enable verbose mode and see where it hangs?

Can you explain the old OpenCore menu?
