### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by Hacarun** [SkyrilHD/Dell-Exx50-Hackintosh#84]
dell latitude e7450 i7 5600u ,intel hd grapics 5500 
os perfecly booting but display backlight is not working , wallpaper doesn't show, wifi&bluetooth not working

**Comment by SkyrilHD** [comment]
Follow this guide for GPU acceleration: https://github.com/SkyrilHD/Dell-E7250-Hackintosh#gpu-acceleration-on-ventura-and-newer

For WiFi: I assume you are on Sequoia, native AirportItlwm does not work yet, you need to switch to itlwm and use the Heliport app
For BT: Enable IntelBluetoothFirmware and BlueToolFixup in the config
