### ISSUE TITLE
Can’t install Sanoma on e5550

### ISSUE THREAD

**Issue by Z-PLAYZ** [SkyrilHD/Dell-Exx50-Hackintosh#85]
I’m trying to install Sanoma on a e5550 and when I click continue to install it says I need an internet connection. I have Ethernet plugged in and I made sure that the next was enabled in opentree. It’s a 5300u with Igpu only
![image](https://github.com/user-attachments/assets/eb1f6481-e8ad-4a7d-8aeb-5b6ec6c50cdd)

**Comment by SkyrilHD** [comment]
That’s weird. Can you check if you can load up Safari?

**Comment by Z-PLAYZ** [comment]
I can't even install the os I wiped my drive due it giving me issues coming from Monterey. I'm gonna try enabling the WiFi nexts and see if I can connect to WiFi and download.

**Comment by SkyrilHD** [comment]
You can still access Safari in the recovery

**Comment by Z-PLAYZ** [comment]
Oh I didn't even notice that. I'll try that next I'm just waiting for it to boot up right now.

**Comment by Z-PLAYZ** [comment]
It's working now but only through WiFi my Ethernet is still not working, the pic shows what was happening before I switched to WiFi. ![image](https://github.com/user-attachments/assets/adffc074-79a2-458b-85a3-40fd498095ab)

**Comment by SkyrilHD** [comment]
Interesting, i think there is an issue when using Ethernet in recovery. Need to confirm it by myself though.

**Comment by Z-PLAYZ** [comment]
I can let yk if it starts working once it's done installing if you want.

**Comment by Z-PLAYZ** [comment]
It got most of the way through the install and now it's just boot looping.

**Comment by SkyrilHD** [comment]
It takes multiple reboots (iirc 4-5) until the installation is finished.

Also how did you format your drive? Make sure you are using APFS instead of HFS (Mac OS Journaled). The installer tries to convert the HFS partition to APFS but it fails as (I assume) the „firmware“ does not support it. Furthermore make sure you format the entire drive instead just the partition (You need to select „Show all disks“ in View).

**Comment by Z-PLAYZ** [comment]
I can't do it rn but when I get home I'll try that. And it also restarted over 10x before I shut it off.

**Comment by Z-PLAYZ** [comment]
I reformatted and got farther then before. The last thing I can read is copying open core files then it starts moving really fast and the laptop restarts and just cycles through that same process over and over.

**Comment by SkyrilHD** [comment]
Make sure the installer reboots at least 4–5 times. You need to select "macOS Installer" until your drive's name shows up.

**Comment by Z-PLAYZ** [comment]
So far it's rebooted 11x and still the same thing.

**Comment by SkyrilHD** [comment]
Hm, something did not work there. Could you do a slow-motion video and check the log where it reboots (I assume you have verbose mode enabled)? Does the boot picker still say "macOS Installer" or does it say the drive's name?

**Comment by Z-PLAYZ** [comment]
Yes I have verbose mode on, and it still says MacOS installer

**Comment by SkyrilHD** [comment]
Can you try changing the SecureBootModel in the config.plist (found in Misc>Security>SecureBootModel)? Change "Default" to "Disabled" (case-sensitive)

**Comment by Z-PLAYZ** [comment]
Yes I will try that and do I need to reformat and restart the install for that. This is a video from most of the restart to the very end right before it shuts off. https://share.icloud.com/photos/0ff8_ZJBzUVPT9EF-2JQYDWyg

**Comment by SkyrilHD** [comment]
Try finishing your existing install first. Your video is still uploading, will check it out later.

**Comment by Z-PLAYZ** [comment]
I'm in the OS now just really slow and my Ethernet is still not working.

**Comment by SkyrilHD** [comment]
Okay, that's progress. The OS is slow due to no GPU acceleration. Follow this guide: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/#gpu-acceleration-on-ventura-and-newer

The guide is a bit outdated, use OpenCore-Patcher.pkg instead.

When you applied root patches, we can check on Ethernet.

**Comment by Z-PLAYZ** [comment]
I got gpu acceleration working but when I go the Ethernet settings they don't exist but show up in search.

**Comment by SkyrilHD** [comment]
Can you download [Hackintool](https://github.com/benbaker76/Hackintool/releases/tag/4.0.3) and send me an export of PCIe?

**Comment by Z-PLAYZ** [comment]
[pcidevices.json](https://github.com/user-attachments/files/18087960/pcidevices.json)
[pcidevices.txt](https://github.com/user-attachments/files/18087961/pcidevices.txt)
those are what it lets me and bluetooth, airdrop, handoff also do not work of what I'm finding. should I mount my efi to my internal storage or wait incase I need to change something?

**Comment by SkyrilHD** [comment]
For Bluetooth, you need to enable IntelBluetoothFirmware and BlueToolFixup in the config. AirDrop and Handoff do not work due to limitation of the Wi-Fi kext. For native Continuity, you need a Broadcom Wi-Fi card.

Your Ethernet is not being detected at all. Check in the BIOS if your NIC is enabled (System Configuration>Integrated NIC). However, if your NIC is already enabled, double-check if IntelMausi is enabled in the config.

**Comment by Z-PLAYZ** [comment]
completely forgot I had to enable the bluetooth kexts I'll go do that. thank you.

**Comment by Z-PLAYZ** [comment]
From Sonoma can I update to sequoia through settings or do I need to do a clean install?

**Comment by SkyrilHD** [comment]
Yes you can update normally through settings

**Comment by Z-PLAYZ** [comment]
Everything's working except WiFi and Bluetooth off what I've found. Is there a way to get them working? I'm on sequoia now.

**Comment by SkyrilHD** [comment]
You need to replace AirportItlwm with itlwm (found [here](https://github.com/OpenIntelWireless/itlwm/releases)). In order to connect to Wi-Fi networks on macOS, you need to use HeliPort (found [here](https://github.com/OpenIntelWireless/HeliPort/releases))
