### ISSUE TITLE
Installer build manifest failed

### ISSUE THREAD

**Issue by KenWuqianghao** [SkyrilHD/Dell-Exx50-Hackintosh#9]
When I click "continue" on installing big sure, "downloading the installer build manifest failed" message pops up after being stuck for a few minutes.

**Comment by SkyrilHD** [comment]
Weird... Try rebooting

**Comment by KenWuqianghao** [comment]
Ok, I'm doing it rignt now.

**Comment by KenWuqianghao** [comment]
After rebooting twice, the same issue comes up.

**Comment by KenWuqianghao** [comment]
Actually, the third try worked. Sorry for the disturbance. This is pretty bizzare

**Comment by SkyrilHD** [comment]
Gotta thank Apple Servers for that lol... After googling this issue, it seems like Apple's servers are overloaded

**Comment by merzzz113** [comment]
i still have the same issue

**Comment by MRzC0DER** [comment]
Me too

**Comment by SkyrilHD** [comment]
Is it via online recovery? If so, it causes issues. Full installer should not cause any issue.
